FROM node:alpine
WORKDIR /app
RUN apk add --no-cache git autoconf automake libtool make tiff jpeg \
                       zlib zlib-dev pkgconf nasm file gcc musl-dev
RUN npm install -g gatsby-cli
COPY ./package*.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "develop"]